# Use official Node.js LTS image
FROM node:20

# Set working directory
WORKDIR /app

# Install dependencies (for caching)
COPY package*.json ./
RUN npm install

# Copy the rest of the project
COPY . .

# Expose Angular's default dev port
EXPOSE 4200

# Start Angular development server
CMD ["npm", "start"]